version: "3"
networks:
  bittery-net-ext:
    external:
      name: docker-compose_bittery-net

services:

  bittery-backend-1:
    restart: unless-stopped
    image: bittery-backend:latest
    container_name: bittery-backend-1
    environment:
      DB_USER: ${DB_USER}
      DB_HOST: ${DB_HOST}
      DB_DATABASE: ${DB_DATABASE}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_PORT: ${DB_PORT}
      ENCRYPTION_PASSWORD_SALT_ROUNDS: ${ENCRYPTION_PASSWORD_SALT_ROUNDS}
      OAUTH2_TOKEN_CLIENT_SECRET: ${OAUTH2_TOKEN_CLIENT_SECRET}
      SESSION_EXPIRES_IN_HOURS: ${SESSION_EXPIRES_IN_HOURS}
      RTL_URL: ${RTL_URL}
      BTCPAY_URL: ${BTCPAY_URL}
      CLIENT_URL_ADDRESS: ${CLIENT_URL_ADDRESS}
      IS_DEVELOPMENT_ENV: ${IS_DEVELOPMENT_ENV}
      DEVELOPMENT_HOSTNAME: ${DEVELOPMENT_HOSTNAME}
      MAILGUN_API_KEY: ${MAILGUN_API_KEY}
      BTCPAY_ADMIN_LOGIN: ${BTCPAY_ADMIN_LOGIN}
      BTCPAY_ADMIN_PASSWORD: ${BTCPAY_ADMIN_PASSWORD}
      PASSWORD_RESET_LINK_VALIDITY_HOURS: ${PASSWORD_RESET_LINK_VALIDITY_HOURS}
      PASSWORD_RESET_EMAIL_HOURS_MEASURE_PERIOD_HOURS: ${PASSWORD_RESET_EMAIL_HOURS_MEASURE_PERIOD_HOURS}
      PASSWORD_RESET_EMAIL_MEASURE_PERIOD_LIMIT: ${PASSWORD_RESET_EMAIL_MEASURE_PERIOD_LIMIT}
      REGISTRATION_ENABLED: ${REGISTRATION_ENABLED}
      LOGIN_ENABLED: ${LOGIN_ENABLED}
      CREATE_INVOICE_ENABLED: ${CREATE_INVOICE_ENABLED}
      BITCOIND_RPC_USER: ${BITCOIND_RPC_USER}
      BITCOIND_RPC_PASSWORD: ${BITCOIND_RPC_PASSWORD}
      BITCOIND_RPC_HOST: ${BITCOIND_RPC_HOST}
      SSH_PRIV_KEY_PATH: ${SSH_PRIV_KEY_PATH}
      LND_HOSTED_FILE_FOLDER_PATH: ${LND_HOSTED_FILE_FOLDER_PATH}
      LND_HOSTED_VERSION: ${LND_HOSTED_VERSION}
      RTL_HOSTED_VERSION: ${RTL_HOSTED_VERSION}
      DIGITAL_OCEAN_SSH_KEY_NAME: ${DIGITAL_OCEAN_SSH_KEY_NAME}
      LND_SUBSCRIPTION_PRICE_USD: ${LND_SUBSCRIPTION_PRICE_USD}
      EMAIL_FOR_ADMIN_NOTIFICATIONS: ${EMAIL_FOR_ADMIN_NOTIFICATIONS}
      DIGITAL_OCEAN_TOKEN: ${DIGITAL_OCEAN_TOKEN}
      BITTERY_NODE_FOR_SUBSCRIPTION_URI: ${BITTERY_NODE_FOR_SUBSCRIPTION_URI}
      APP_PORT: ${APP_PORT}
      RUN_STATIC_CHANNEL_BACKUP_SCHEDULER: ${RUN_STATIC_CHANNEL_BACKUP_SCHEDULER_BACKEND_1}
      RUN_SUBSCRIPTION_DISABLE_SCHEDULER: ${RUN_SUBSCRIPTION_DISABLE_SCHEDULER_BACKEND_1}
      RUN_SUBSCRIPTION_RENEW_EMAIL_SCHEDULER: ${RUN_SUBSCRIPTION_RENEW_EMAIL_SCHEDULER_BACKEND_1}
      CUSTOM_LOGO_BTCPAY_URL: ${CUSTOM_LOGO_BTCPAY_URL}
      CUSTOM_CSS_BTCPAY_URL: ${CUSTOM_CSS_BTCPAY_URL}
      BTCPAY_ADMIN_API_KEY: ${BTCPAY_ADMIN_API_KEY}
      BTCPAY_BACKEND_ONLY_URL: ${BTCPAY_BACKEND_ONLY_URL}
      BITTERY_SUBSCRIPTION_PAYMENTS_STORE_ID: ${BITTERY_SUBSCRIPTION_PAYMENTS_STORE_ID}
      BTCPAY_FACADE_WEBHOOK_URL: ${BTCPAY_FACADE_WEBHOOK_URL}
      BTCPAY_FACADE_WEBHOOK_SECRET: ${BTCPAY_FACADE_WEBHOOK_SECRET}
      BITCOIND_RPC_HOST_FROM_INTERNET: ${BITCOIND_RPC_HOST_FROM_INTERNET}
      RECAPTCHA_SITE_KEY: ${RECAPTCHA_SITE_KEY}
      RECAPTCHA_SECRET_KEY: ${RECAPTCHA_SECRET_KEY}
    networks:
      - bittery-net-ext
    volumes:
      - ${SSH_PRIV_KEY_PATH_ON_HOST}:${SSH_PRIV_KEY_PATH}:ro
      - ../volumes/bittery-backend/lnd_hosted_files/bittery_backend_1:${LND_HOSTED_FILE_FOLDER_PATH}:rw
    ports:
      - 3000:3000

#  bittery-backend-2:
#    restart: unless-stopped
#    image: bitteryio/bittery-backend:0.2.2
#    container_name: bittery-backend-2
#    environment:
#      DB_USER: ${POSTGRES_USER}
#      DB_HOST: ${DB_HOST}
#      DB_DATABASE: ${POSTGRES_DB}
#      DB_PASSWORD: ${POSTGRES_PASSWORD}
#      DB_PORT: ${DB_PORT}
#      ENCRYPTION_PASSWORD_SALT_ROUNDS: ${ENCRYPTION_PASSWORD_SALT_ROUNDS}
#      OAUTH2_TOKEN_CLIENT_SECRET: ${OAUTH2_TOKEN_CLIENT_SECRET}
#      SESSION_EXPIRES_IN_HOURS: ${SESSION_EXPIRES_IN_HOURS}
#      RTL_URL: ${RTL_URL}
#      BTCPAY_URL: ${BTCPAY_URL}
#      CLIENT_URL_ADDRESS: ${CLIENT_URL_ADDRESS}
#      IS_DEVELOPMENT_ENV: ${IS_DEVELOPMENT_ENV}
#      DEVELOPMENT_HOSTNAME: ${DEVELOPMENT_HOSTNAME}
#      MAILGUN_API_KEY: ${MAILGUN_API_KEY}
#      BTCPAY_ADMIN_LOGIN: ${BTCPAY_ADMIN_LOGIN}
#      BTCPAY_ADMIN_PASSWORD: ${BTCPAY_ADMIN_PASSWORD}
#      PASSWORD_RESET_LINK_VALIDITY_HOURS: ${PASSWORD_RESET_LINK_VALIDITY_HOURS}
#      PASSWORD_RESET_EMAIL_HOURS_MEASURE_PERIOD_HOURS: ${PASSWORD_RESET_EMAIL_HOURS_MEASURE_PERIOD_HOURS}
#      PASSWORD_RESET_EMAIL_MEASURE_PERIOD_LIMIT: ${PASSWORD_RESET_EMAIL_MEASURE_PERIOD_LIMIT}
#      REGISTRATION_ENABLED: ${REGISTRATION_ENABLED}
#      LOGIN_ENABLED: ${LOGIN_ENABLED}
#      CREATE_INVOICE_ENABLED: ${CREATE_INVOICE_ENABLED}
#      BITCOIND_RPC_USER: ${BITCOIND_RPC_USER}
#      BITCOIND_RPC_PASSWORD: ${BITCOIND_RPC_PASSWORD}
#      BITCOIND_RPC_HOST: ${BITCOIND_RPC_HOST}
#      SSH_PRIV_KEY_PATH: ${SSH_PRIV_KEY_PATH}
#      LND_HOSTED_FILE_FOLDER_PATH: ${LND_HOSTED_FILE_FOLDER_PATH}
#      LND_HOSTED_VERSION: ${LND_HOSTED_VERSION}
#      RTL_HOSTED_VERSION: ${RTL_HOSTED_VERSION}
#      DIGITAL_OCEAN_SSH_KEY_NAME: ${DIGITAL_OCEAN_SSH_KEY_NAME}
#      LND_SUBSCRIPTION_PRICE_USD: ${LND_SUBSCRIPTION_PRICE_USD}
#      EMAIL_FOR_ADMIN_NOTIFICATIONS: ${EMAIL_FOR_ADMIN_NOTIFICATIONS}
#      DIGITAL_OCEAN_TOKEN: ${DIGITAL_OCEAN_TOKEN}
#      BITTERY_NODE_FOR_SUBSCRIPTION_URI: ${BITTERY_NODE_FOR_SUBSCRIPTION_URI}
#      APP_PORT: ${APP_PORT}
#      RUN_STATIC_CHANNEL_BACKUP_SCHEDULER: ${RUN_STATIC_CHANNEL_BACKUP_SCHEDULER_BACKEND_2}
#      RUN_SUBSCRIPTION_DISABLE_SCHEDULER: ${RUN_SUBSCRIPTION_DISABLE_SCHEDULER_BACKEND_2}
#      RUN_SUBSCRIPTION_RENEW_EMAIL_SCHEDULER: ${RUN_SUBSCRIPTION_RENEW_EMAIL_SCHEDULER_BACKEND_2}
#      CUSTOM_LOGO_BTCPAY_URL: ${CUSTOM_LOGO_BTCPAY_URL}
#      CUSTOM_CSS_BTCPAY_URL: ${CUSTOM_CSS_BTCPAY_URL}
#      BTCPAY_ADMIN_API_KEY: ${BTCPAY_ADMIN_API_KEY}
#      BTCPAY_BACKEND_ONLY_URL: ${BTCPAY_BACKEND_ONLY_URL}
#      BITTERY_SUBSCRIPTION_PAYMENTS_STORE_ID: ${BITTERY_SUBSCRIPTION_PAYMENTS_STORE_ID}
#      BTCPAY_FACADE_WEBHOOK_URL: ${BTCPAY_FACADE_WEBHOOK_URL}
#      BTCPAY_FACADE_WEBHOOK_SECRET: ${BTCPAY_FACADE_WEBHOOK_SECRET}
#      BITCOIND_RPC_HOST_FROM_INTERNET: ${BITCOIND_RPC_HOST_FROM_INTERNET}
#      RECAPTCHA_SITE_KEY: ${RECAPTCHA_SITE_KEY}
#      RECAPTCHA_SECRET_KEY: ${RECAPTCHA_SECRET_KEY}
#    volumes:
##      - ${SSH_PRIV_KEY_PATH_ON_HOST}:${SSH_PRIV_KEY_PATH}:ro
#      - ../volumes/bittery-backend/lnd_hosted_files/bittery_backend_2:$LND_HOSTED_FILE_FOLDER_PATH:rw
#    networks:
#      - bittery-net-ext
#    expose:
#      - 3000
